### ISSUE TITLE
HKey -  slice out of bounds error - with dmap put

### ISSUE THREAD

**Issue by mattdurham** [buraksezer/olric#166]
When calling dmap.put with the embedded client, I am getting an out-of-bounds error in hkey.go(actually in the hasher, but this is the root of the error), changing the code to
```
func HKey(name, key string) uint64 {
	tmp := name + key
	return hashFunc.Sum64([]byte(tmp))
}
```
resolves the error.

**Comment by buraksezer** [comment]
Hi @mattdurham 

Thank you for reporting this.

Which Olric version are you using? How can I reproduce this error? I have never seen this error. The current version of the `HKey` function uses `unsafe` package to reduce memory consumption. Removing this will increase the GC pressure. So I need the input you use to reproduce the problem.

**Comment by mattdurham** [comment]
More interesting, it fails if I have the debugger attached but succeeds if not.

**Comment by mattdurham** [comment]
I think it's a behavior on M1, my x64 box exhibited no bad behavior. Alright if I submit a PR to revert to slower method if its arm arch/os osx?

**Comment by buraksezer** [comment]
I managed to reproduce the error on a Macbook with an M1 processor.

As you can see, there is a bug in [cespare/xxhash](https://github.com/cespare/xxhash/blob/e7a6b52374f7e2abfb8abb27249d53a1997b09a7/xxhash_other.go#L41). We should report this bug to the author. 

You can also use a different hash implementation by implementing the `hasher.Hasher` interface. `config.Config` has an `Hasher` field.

Configuration: https://github.com/buraksezer/olric/blob/master/config/config.go#L258
The default hasher implementation: https://github.com/buraksezer/olric/blob/e0a16290aa590b4bdf441176ca6b9510421eb763/hasher/hasher.go#L21

What do you think? By the way, I would like to be happy to learn more about your use case, if it's possible to talk about it publicly. 

Here is the output:
```
=== RUN   TestClusterClient_Delete
2022/05/25 00:52:26 [INFO] Olric 0.5.0-beta.3 on darwin/arm64 go1.18.1 => olric.go:313
2022/05/25 00:52:26 [DEBUG] memberlist: Using dynamic bind port 49369
2022/05/25 00:52:26 [INFO] Join completed. Synced with 0 initial nodes => discovery.go:59
2022/05/25 00:52:26 [INFO] Routing table has been pushed by 127.0.0.1:49368 => operations.go:86
2022/05/25 00:52:26 [INFO] The cluster coordinator has been bootstrapped => discovery.go:42
2022/05/25 00:52:26 [INFO] Memberlist bindAddr: 127.0.0.1, bindPort: 49369 => routingtable.go:413
2022/05/25 00:52:26 [INFO] Cluster coordinator: 127.0.0.1:49368 => routingtable.go:414
2022/05/25 00:52:26 [INFO] Node name in the cluster: 127.0.0.1:49368 => olric.go:374
2022/05/25 00:52:26 [INFO] Olric bindAddr: 127.0.0.1, bindPort: 49368 => olric.go:380
2022/05/25 00:52:26 [INFO] Replication count is 1 => olric.go:382
    olric_test.go:110: A new cluster member has been created: 127.0.0.1:49368
panic: runtime error: slice bounds out of range [::11] with capacity 0

goroutine 41 [running]:
github.com/cespare/xxhash/v2.Sum64({0x140000298f0, 0xb, 0x0})
	/Users/buraksezer/go/pkg/mod/github.com/cespare/xxhash/v2@v2.1.2/xxhash_other.go:41 +0x3f0
github.com/buraksezer/olric/hasher.xxhasher.Sum64({}, {0x140000298f0, 0xb, 0x0})
	/Users/buraksezer/go/src/github.com/buraksezer/olric/hasher/hasher.go:28 +0x3c
github.com/buraksezer/olric/internal/cluster/partitions.HKey({0x14000026894, 0x6}, {0x140000268a0, 0x5})
	/Users/buraksezer/go/src/github.com/buraksezer/olric/internal/cluster/partitions/hkey.go:37 +0x90
github.com/buraksezer/olric/internal/dmap.(*DMap).put(0x140001ce200, 0x14000192600)
	/Users/buraksezer/go/src/github.com/buraksezer/olric/internal/dmap/put.go:357 +0x6c
github.com/buraksezer/olric/internal/dmap.(*Service).putCommandHandler(0x140001682d0, {0x1013ffa48, 0x140000ed880}, {{0x14000026880, 0x34, 0x40}, {0x14000094de0, 0x4, 0x4}})
	/Users/buraksezer/go/src/github.com/buraksezer/olric/internal/dmap/put_handlers.go:62 +0x3f4
github.com/buraksezer/olric/internal/server.Handler.ServeRESP({0x14000110a30, 0x140001108a0}, {0x1013ffa48, 0x140000ed880}, {{0x14000026880, 0x34, 0x40}, {0x14000094de0, 0x4, 0x4}})
	/Users/buraksezer/go/src/github.com/buraksezer/olric/internal/server/handler.go:68 +0x4b0
github.com/buraksezer/olric/internal/server.(*ServeMux).ServeRESP(0x1400011c088, {0x1013ffa48, 0x140000ed880}, {{0x14000026880, 0x34, 0x40}, {0x14000094de0, 0x4, 0x4}})
	/Users/buraksezer/go/src/github.com/buraksezer/olric/internal/server/mux.go:73 +0x11c
github.com/tidwall/redcon.handle.func2(0x140000ed880, 0x140001579d0)
	/Users/buraksezer/go/pkg/mod/github.com/tidwall/redcon@v1.4.5/redcon.go:429 +0x3b8
github.com/tidwall/redcon.handle(0x140001579d0, 0x140000ed880)
	/Users/buraksezer/go/pkg/mod/github.com/tidwall/redcon@v1.4.5/redcon.go:442 +0x94
created by github.com/tidwall/redcon.serve
	/Users/buraksezer/go/pkg/mod/github.com/tidwall/redcon@v1.4.5/redcon.go:378 +0x53c

Debugger finished with the exit code 0
```

**Comment by maxid** [comment]
> Thank you @mattdurham for the update. Please don't hesitate to ask questions about the design of Olric and potential integration problems. We also have a Discord channel, it's good for instant communication: https://discord.com/invite/ahK7Vjr8We

```golang
type fixedhasher struct{}

func (m fixedhasher) Sum64(key []byte) uint64 {
	return xxhash.Sum64([]byte(string(key))) // use xxhash.Sum64([]byte(string(key))) replace xxhash.Sum64(key) can fixed this problem
}
```
