### ISSUE TITLE
panic on args

### ISSUE THREAD

**Issue by derekperkins** [buraksezer/olric#214]
This is similar to #208, but panics in the arg creation, not `execOnPipeline` itself. Possible it is an upstream issue, I haven't looked into it.

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdc2380]

goroutine 2150125 [running]:
github.com/go-redis/redis/v8.(*StringCmd).Args(0x1fc4ae0?)
	<autogenerated>:1
github.com/buraksezer/olric.(*DMapPipeline).execOnPartition(0xc00360a9c0, {0x2ae6c28, 0xc0056d4150}, 0xc000e0f750?)
	/Users/derek/go/pkg/mod/github.com/buraksezer/olric@v0.5.2/pipeline.go:483 +0x322
github.com/buraksezer/olric.(*DMapPipeline).Exec.func1()
	/Users/derek/go/pkg/mod/github.com/buraksezer/olric@v0.5.2/pipeline.go:532 +0x6e
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/Users/derek/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
```

**Comment by buraksezer** [comment]
This is not possible to debug on my side. `NewStringCmd` can take a nil argument. This is how it is created: 

```go
func NewStringCmd(ctx context.Context, args ...interface{}) *StringCmd {
	return &StringCmd{
		baseCmd: baseCmd{
			ctx:  ctx,
			args: args,
		},
	}
}
```

It seems that if `args` contains a `nil`, it can lead to a panic in production.
