### ISSUE TITLE
As a new member joined to the olric cluster, a node crashed

### ISSUE THREAD

**Issue by cobexer** [buraksezer/olric#59]
```
[DEBUG] memberlist: Stream connection from=10.128.9.36:57596
[INFO] Node joined: 10.128.9.36:4220
[INFO] Routing table has been pushed by 10.130.7.54:4220
[...]
[INFO] Moving dmap: kvcache (backup: true) on PartID: 206 to 10.130.7.54:4220
[INFO] Moving dmap: kvcache (backup: true) on PartID: 209 to 10.130.7.54:4220
panic: runtime error: makeslice: len out of range

goroutine 19037 [running]:
github.com/buraksezer/olric/internal/protocol.(*DMapMessage).Decode(0xc0002c2e40, 0xc00acfb110, 0x2eaa380)
	/go/pkg/mod/github.com/buraksezer/olric@v0.3.0-beta.3/internal/protocol/dmap.go:233 +0x2e3
github.com/buraksezer/olric/internal/transport.(*Client).RequestTo(0xc00040b2c0, 0xc009730970, 0x10, 0x2eaa380, 0xc00a9bf860, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/buraksezer/olric@v0.3.0-beta.3/internal/transport/client.go:258 +0x2d3
github.com/buraksezer/olric.(*Olric).requestTo(0xc00044eea0, 0xc009730970, 0x10, 0x2eaa380, 0xc00a9bf860, 0x0, 0x1, 0x0, 0x0)
	/go/pkg/mod/github.com/buraksezer/olric@v0.3.0-beta.3/olric.go:462 +0x6a
github.com/buraksezer/olric.(*Olric).asyncPutOnCluster.func1(0xc00044eea0, 0xc00a9bf860, 0xc009730970, 0x10, 0x2c32a9416ab0e016, 0x16399cb3353d6220)
	/go/pkg/mod/github.com/buraksezer/olric@v0.3.0-beta.3/dmap_put.go:162 +0x91
created by github.com/buraksezer/olric.(*Olric).asyncPutOnCluster
	/go/pkg/mod/github.com/buraksezer/olric@v0.3.0-beta.3/dmap_put.go:160 +0x142
```

**Comment by buraksezer** [comment]
I have investigated the problem. It looks like a data race in `asyncPutOnCluster` function. I immediately implemented a fix and relased **v0.3.0-beta.4**. Could you please try to repeat the problem?

**Comment by cobexer** [comment]
I updated to v0.3.0-beta.4 and can't reproduce the problem anymore!

v0.3.0-beta.4 seems to also solve 3 issues of #54:
* writes often fail with network I/O timeouts
* one member uses ~100% of a CPU all the time
* memory use seems very high

Nice!

**Comment by buraksezer** [comment]
I'm closing this issue. If the problem still persists, please feel free to open the issue.
